;ROLL => 194201
;FINONACCI SEQUENCE
MOV AL, 00H ;FIRST TERM
MOV SI, 0C900H ;ADDRESS WHERE TERMS WILL BE STORED

MOV [SI], AL ;STORE AT POINTER LOCATION
INC SI
INC AL 
MOV [SI], AL;

MOV CL, 05H ;NUMBER OF STEPS     
SUB CL, 02H ;2 TERMS ARE ALREADY PRESENT 

FIB: MOV AL, [SI-1] ;MAKE AX THE PREV VALUE
ADD AL, [SI] ;ADD CURRENT VALUE TO PREV VALUE
INC SI
MOV [SI], AL
DEC CL
JNZ FIB
HLT