;ROLL => 194201
;ASCENDING SORT OF ARRAY
MOV CL, 04H ;OUTER LOOP CONTROL VARIABLE
DEC CL
I: MOV SI, 0C900H ;201 IN DEC => C9 IN HEX 
MOV CH, 04 ;INNER LOOP CONTROL VARIABLE
DEC CH
J: MOV AL, [SI]
INC SI
CMP AL, [SI] ;COMPARING 2 ADJ ELEMENTS
JC ITER ;CF IS 1 IF AX < SI
XCHG AL, [SI] ;NEXT 4 LINES 
DEC SI        ;SWAP IF AX > SI
XCHG AL, [SI]
INC SI
ITER: DEC CH
JNZ J
DEC CL
JNZ I
HLT ;HALT



